
spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/

#配置日志文件参数
logging:
  file:
    path: F:/mylog/eurekaClient9003Log
  level:
    org:
      springframework:
        security: DEBUG
