
spring:
  application:
    name: spring-cloud-eureka

server:
  port: 9002


eureka:
  instance:
    hostname: localhost
  client:
    #这下面两个false表示Eureka服务注册中心
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#配置日志文件参数
logging:
  file:
    path: F:/mylog/eurekaServer9002Log
  level:
    org:
      springframework:
        security: DEBUG
