
spring:
  application:
    name: spring-cloud-eureka
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9002

eureka:
  instance:
    hostname: localhost
  client:
    #这下面两个false表示Eureka服务注册中心{集群不设置false，默认为true}
    #registerWithEureka: false
    #fetchRegistry: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
#配置日志文件参数
logging:
  file:
    path: F:/mylog/eurekaServer9002Log
  level:
    org:
      springframework:
        security: DEBUG
