
spring:
  application:
    name: spring-cloud-eureka
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9002

eureka:
  instance:
    hostname: localhost
    #使用IP注册(集群模式肯定多机器不同ip,，但是我单机多进程)
    #prefer-ip-address: true
    # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    lease-expiration-duration-in-seconds: 20
  client:
    #这下面两个false表示Eureka服务注册中心{集群不设置false，默认为true}
    #registerWithEureka: false
    #fetchRegistry: false
    #注册自身到eureka服务器
    registerWithEureka: true
    # 表示是否从eureka服务器获取注册信息
    fetchRegistry: false
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 5
    # 设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
  server:
    #renewal-percent-threshold: 0.1
    # 关闭自我保护模式
    enable-self-preservation: false
    # Eureka Server 自我保护系数，当enable-self-preservation=true时，启作用
    # renewal-percent-threshold:
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 6000000
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 60000





#配置日志文件参数
logging:
  file:
    path: F:/mylog/eurekaServer9002Log
  level:
    org:
      springframework:
        security: DEBUG
