
spring:
  # freemarker:
  #prefer-file-system-access: false
  application:
    name: spring-cloud-eureka-test
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        #解决使用其他库的表时候，把小数点变成下划线，导致sql无法成功执行。
        #这是由于物理命名策略引起的，大写字母变小写，加_下划线（hibernate5以上高版本）
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
  #thymeleaf模板配置
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  #静态资源路径
  mvc:
    static-path-pattern: /static/**

  #redis配置参数
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 30
        max-wait: -1ms
        max-idle: 16
        min-idle: 0
    timeout: 3000ms
  #mongodb配置参数
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      uri: mongodb://127.0.0.1/test
      repositories:
        type: auto
      #mongodb plus
      option:
        socket-keep-alive: true
        max-connection-idle-time: 60000
        connect-timeout: 36000
        min-connection-per-host: 5
        threads-allowed-to-block-for-connection-multiplier: 5
        max-wait-time: 120000
        socket-timeout: 0
        max-connection-life-time: 0
        heartbeat-connect-timeout: 36000
        heartbeat-socket-timeout: 36000
        min-heartbeat-frequency: 5
        heartbeat-frequency: 10
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wupeng
    password: wp19960615
    virtual-host: /
    #rabbitmq消息确认
    publisher-confirms: true
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #手动确认
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 3 #同一个队列启动几个消费者
        max-concurrency: 3 #启动消费者最大数量
        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5
          stateless: false
          #时间策略乘数因子
          multiplier: 1.0
          initial-interval: 1000ms
          max-interval: 10000ms
        default-requeue-rejected: true





#配置日志文件参数
logging:
  file:
    path: F:/mylog/cloudlog
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG
    com:
      looedu:
        mapper: debug


