#redis
spring:
  application:
    name: spring-cloud-redis
  zipkin:
    base-url: http://localhost:9411
  #redis配置参数
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000ms
    jedis:
      pool:
        max-active: 30
        max-wait: -1ms
        max-idle: 16
        min-idle: 0


server:
  port: 8558

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka

#配置日志文件参数
logging:
  file:
    path: F:/mylog/redis8558Log
  level:
    org:
      springframework:
        security: DEBUG
