
spring:
  application:
    name: spring-cloud-eureka-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9051

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/

#配置日志文件参数
logging:
  file:
    path: F:/mylog/ribbon9051Log
  level:
    org:
      springframework:
        security: DEBUG
