
spring:
  application:
    name: spring-cloud-eureka-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9061

#开启熔断器
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/

#配置日志文件参数
logging:
  file:
    path: F:/mylog/feign9061Log
  level:
    org:
      springframework:
        security: DEBUG
